INSERT INTO `leagues` (`id`, `name`, `short_name`, `gender`, `source`, `old_db_league_id`, `sp_term_id`, `old_db_id`) VALUES
(1, 'Bay State Carey', NULL, 'M', NULL, NULL, NULL, 3),
(2, 'Bay State Herget', NULL, 'M', NULL, NULL, NULL, 4),
(3, 'Pioneer Valley Berry Division', NULL, 'M', NULL, NULL, NULL, 5),
(4, 'Big Three', NULL, 'M', NULL, NULL, NULL, 6),
(5, 'Boston City League', NULL, 'M', NULL, NULL, NULL, 7),
(6, 'Cape Ann League', NULL, 'M', NULL, NULL, NULL, 8),
(7, 'Catholic  Conference', NULL, 'M', NULL, NULL, NULL, 9),
(8, 'Catholic Central I', NULL, 'M', NULL, NULL, NULL, 10),
(9, 'Catholic Central II', NULL, 'M', NULL, NULL, NULL, 11),
(10, 'Commonwealth Athletic Conf.', NULL, 'M', NULL, NULL, NULL, 12),
(11, 'Central Mass Coughlin Conf.', NULL, 'M', NULL, NULL, NULL, 13),
(12, 'Eastern Athletic Conference', NULL, 'M', NULL, NULL, NULL, 14),
(13, 'Pioneer Valley Fay Division', NULL, 'M', NULL, NULL, NULL, 15),
(14, 'Greater Boston League', NULL, 'M', NULL, NULL, NULL, 16),
(15, 'Berkshire County Hennessy League', NULL, 'M', NULL, NULL, NULL, 17),
(16, 'Hockomock Kelley-Rex Division', NULL, 'M', NULL, NULL, NULL, 18),
(17, 'Independent', NULL, 'M', NULL, NULL, NULL, 19),
(18, 'Mayflower League', NULL, 'M', NULL, NULL, NULL, 20),
(19, 'Merrimack Valley/Dual County Div 1', NULL, 'M', NULL, NULL, NULL, 21),
(20, 'Merrimack Valley/Dual County Div 2', NULL, 'M', NULL, NULL, NULL, 22),
(21, 'Merrimack Valley/Dual County Div 3', NULL, 'M', NULL, NULL, NULL, 23),
(22, 'Middlesex League Liberty Division', NULL, 'M', NULL, NULL, NULL, 24),
(23, 'Northeastern North', NULL, 'M', NULL, NULL, NULL, 25),
(24, 'Northeastern South', NULL, 'M', NULL, NULL, NULL, 27),
(25, 'Old Colony League', NULL, 'M', NULL, NULL, NULL, 28),
(26, 'Patriot League Fisher Division', NULL, 'M', NULL, NULL, NULL, 29),
(27, 'Central Mass Quinn Conf.', NULL, 'M', NULL, NULL, NULL, 30),
(28, 'Central Mass Roy Conf.', NULL, 'M', NULL, NULL, NULL, 31),
(29, 'Central Mass Russell Conf.', NULL, 'M', NULL, NULL, NULL, 32),
(30, 'South Coast Conference', NULL, 'M', NULL, NULL, NULL, 33),
(31, 'South Shore League', NULL, 'M', NULL, NULL, NULL, 34),
(32, 'Tri-Valley League Large', NULL, 'M', NULL, NULL, NULL, 35),
(33, 'Pioneer Valley Wright Division', NULL, 'M', NULL, NULL, NULL, 36),
(34, 'Bay State Carey', NULL, 'F', NULL, NULL, NULL, 37),
(35, 'Bay State Herget', NULL, 'F', NULL, NULL, NULL, 38),
(36, 'Catholic Central League', NULL, 'F', NULL, NULL, NULL, 39),
(37, 'Catholic Conference', NULL, 'F', NULL, NULL, NULL, 40),
(38, 'Merrimack Valley/Dual County Large', NULL, 'F', NULL, NULL, NULL, 41),
(39, 'Merrimack Valley Conference/Greater Boston League', NULL, 'F', NULL, NULL, NULL, 42),
(40, 'Northeastern Hockey League', NULL, 'F', NULL, NULL, NULL, 43),
(41, 'Independent', NULL, 'F', NULL, NULL, NULL, 44),
(42, 'Middlesex League Liberty Division', NULL, 'F', NULL, NULL, NULL, 45),
(43, 'NORTH CAPE', NULL, 'F', NULL, NULL, NULL, 46),
(44, 'SEMGHL West', NULL, 'F', NULL, NULL, NULL, 47),
(45, 'SEMGHL Coastal', NULL, 'F', NULL, NULL, NULL, 48),
(46, 'Atlantic Coast League', NULL, 'M', NULL, NULL, NULL, 50),
(47, 'Dual County Small', NULL, 'F', NULL, NULL, NULL, 51),
(48, 'Catholic West Hockey Conference', NULL, 'M', NULL, NULL, NULL, 52),
(49, 'Greater Boston League', NULL, 'F', NULL, NULL, NULL, 53),
(50, 'Merrimack Valley/Dual County Small', NULL, 'F', NULL, NULL, NULL, 54),
(51, 'Catholic West Hockey Conference', NULL, 'M', NULL, NULL, NULL, 55),
(52, 'Dual County Small', NULL, 'F', NULL, NULL, NULL, 56),
(53, 'Bay State Carey', NULL, 'M', NULL, NULL, NULL, 57),
(54, 'Bay State Herget', NULL, 'M', NULL, NULL, NULL, 58),
(55, 'Pioneer Valley Berry Division', NULL, 'M', NULL, NULL, NULL, 59),
(56, 'Big Three', NULL, 'M', NULL, NULL, NULL, 60),
(57, 'Boston City', NULL, 'M', NULL, NULL, NULL, 61),
(58, 'Cape Ann League', NULL, 'M', NULL, NULL, NULL, 62),
(59, 'Catholic  Conference', NULL, 'M', NULL, NULL, NULL, 63),
(60, 'Catholic Central I', NULL, 'M', NULL, NULL, NULL, 64),
(61, 'Catholic Central II', NULL, 'M', NULL, NULL, NULL, 65),
(62, 'Commonwealth Athletic Conference', NULL, 'M', NULL, NULL, NULL, 66),
(63, 'Central Mass. Coughlin Conference', NULL, 'M', NULL, NULL, NULL, 67),
(64, 'Eastern Athletic Conference', NULL, 'M', NULL, NULL, NULL, 68),
(65, 'Pioneer Valley Fay Division', NULL, 'M', NULL, NULL, NULL, 69),
(66, 'Greater Boston League', NULL, 'M', NULL, NULL, NULL, 70),
(67, 'Berkshire County Hennessey League', NULL, 'M', NULL, NULL, NULL, 71),
(68, 'Hockomock', NULL, 'M', NULL, NULL, NULL, 72),
(69, 'Independent', NULL, 'M', NULL, NULL, NULL, 73),
(70, 'Mayflower League', NULL, 'M', NULL, NULL, NULL, 74),
(71, 'MerrimackValley/Dual County Div 1', NULL, 'M', NULL, NULL, NULL, 75),
(72, 'MerrimackValley/Dual County Div 2', NULL, 'M', NULL, NULL, NULL, 76),
(73, 'MerrimackValley/Dual County Div 3', NULL, 'M', NULL, NULL, NULL, 77),
(74, 'Middlesex League', NULL, 'M', NULL, NULL, NULL, 78),
(75, 'Northeastern North Div 2', NULL, 'M', NULL, NULL, NULL, 79),
(76, 'Northeastern South Div 3', NULL, 'M', NULL, NULL, NULL, 80),
(77, 'Old Colony League', NULL, 'M', NULL, NULL, NULL, 81),
(78, 'Patriot League', NULL, 'M', NULL, NULL, NULL, 82),
(79, 'Central Mass. Quinn Conference', NULL, 'M', NULL, NULL, NULL, 83),
(80, 'Central Mass. Roy Conference', NULL, 'M', NULL, NULL, NULL, 84),
(81, 'Central Mass. Russell Conference', NULL, 'M', NULL, NULL, NULL, 85),
(82, 'South Coast League', NULL, 'M', NULL, NULL, NULL, 86),
(83, 'South Shore League', NULL, 'M', NULL, NULL, NULL, 87),
(84, 'Tri-Valley League', NULL, 'M', NULL, NULL, NULL, 88),
(85, 'Pioneer Valley Wright Division', NULL, 'M', NULL, NULL, NULL, 89),
(86, 'Bay State Carey', NULL, 'F', NULL, NULL, NULL, 90),
(87, 'Bay State Herget', NULL, 'F', NULL, NULL, NULL, 91),
(88, 'Catholic Central League', NULL, 'F', NULL, NULL, NULL, 92),
(89, 'Catholic Conference', NULL, 'F', NULL, NULL, NULL, 93),
(90, 'Merrimack Valley/Dual County Large', NULL, 'F', NULL, NULL, NULL, 94),
(91, 'Merrimack Valley Conference/Greater Boston League', NULL, 'F', NULL, NULL, NULL, 95),
(92, 'North Cape League', NULL, 'F', NULL, NULL, NULL, 96),
(93, 'Independent', NULL, 'F', NULL, NULL, NULL, 97),
(94, 'Middlesex', NULL, 'F', NULL, NULL, NULL, 98),
(95, 'NORTH CAPE', NULL, 'F', NULL, NULL, NULL, 99),
(96, 'Southeastern Mass GHL North', NULL, 'F', NULL, NULL, NULL, 100),
(97, 'Southeastern Mass GHL South', NULL, 'F', NULL, NULL, NULL, 101),
(98, 'Atlantic Coast', NULL, 'M', NULL, NULL, NULL, 102),
(99, 'Greater Boston League', NULL, 'F', NULL, NULL, NULL, 103),
(100, 'Merrimack Valley/Dual County Small', NULL, 'F', NULL, NULL, NULL, 104),
(101, 'Hockomock Davenport Division', NULL, 'M', NULL, NULL, NULL, 105),
(102, 'GEMIHL Northeast', NULL, 'F', NULL, NULL, NULL, 106),
(103, 'Central/West', NULL, 'F', NULL, NULL, NULL, 107),
(104, 'Catholic West Hockey Conference', NULL, 'M', NULL, NULL, NULL, 108),
(105, 'Dual County Small', NULL, 'F', NULL, NULL, NULL, 109),
(106, 'Bay State Carey', NULL, 'M', NULL, NULL, NULL, 110),
(107, 'Bay State Herget', NULL, 'M', NULL, NULL, NULL, 111),
(108, 'Pioneer Valley Berry Division', NULL, 'M', NULL, NULL, NULL, 112),
(109, 'Big Three', NULL, 'M', NULL, NULL, NULL, 113),
(110, 'Boston City', NULL, 'M', NULL, NULL, NULL, 114),
(111, 'Cape Ann League', NULL, 'M', NULL, NULL, NULL, 115),
(112, 'Catholic  Conference', NULL, 'M', NULL, NULL, NULL, 116),
(113, 'Catholic Central I', NULL, 'M', NULL, NULL, NULL, 117),
(114, 'Catholic Central II', NULL, 'M', NULL, NULL, NULL, 118),
(115, 'Commonwealth Athletic Conference', NULL, 'M', NULL, NULL, NULL, 119),
(116, 'Central Mass. Coughlin Conference', NULL, 'M', NULL, NULL, NULL, 120),
(117, 'Eastern Athletic Conference', NULL, 'M', NULL, NULL, NULL, 121),
(118, 'Pioneer Valley Fay Division', NULL, 'M', NULL, NULL, NULL, 122),
(119, 'Greater Boston League', NULL, 'M', NULL, NULL, NULL, 123),
(120, 'Berkshire County Hennessey League', NULL, 'M', NULL, NULL, NULL, 124),
(121, 'Hockomock', NULL, 'M', NULL, NULL, NULL, 125),
(122, 'Independent', NULL, 'M', NULL, NULL, NULL, 126),
(123, 'Mayflower League', NULL, 'M', NULL, NULL, NULL, 127),
(124, 'MerrimackValley/Dual County Div 1', NULL, 'M', NULL, NULL, NULL, 128),
(125, 'MerrimackValley/Dual County Div 2', NULL, 'M', NULL, NULL, NULL, 129),
(126, 'MerrimackValley/Dual County Div 3', NULL, 'M', NULL, NULL, NULL, 130),
(127, 'Middlesex League', NULL, 'M', NULL, NULL, NULL, 131),
(128, 'Northeastern North Div 2', NULL, 'M', NULL, NULL, NULL, 132),
(129, 'Northeastern South Div 3', NULL, 'M', NULL, NULL, NULL, 133),
(130, 'Old Colony League', NULL, 'M', NULL, NULL, NULL, 134),
(131, 'Patriot League', NULL, 'M', NULL, NULL, NULL, 135),
(132, 'Central Mass. Quinn Conference', NULL, 'M', NULL, NULL, NULL, 136),
(133, 'Central Mass. Roy Conference', NULL, 'M', NULL, NULL, NULL, 137),
(134, 'Central Mass. Russell Conference', NULL, 'M', NULL, NULL, NULL, 138),
(135, 'South Coast League', NULL, 'M', NULL, NULL, NULL, 139),
(136, 'South Shore League', NULL, 'M', NULL, NULL, NULL, 140),
(137, 'Tri-Valley League', NULL, 'M', NULL, NULL, NULL, 141),
(138, 'Pioneer Valley Wright Division', NULL, 'M', NULL, NULL, NULL, 142),
(139, 'Bay State Carey', NULL, 'F', NULL, NULL, NULL, 143),
(140, 'Bay State Herget', NULL, 'F', NULL, NULL, NULL, 144),
(141, 'Catholic Central League', NULL, 'F', NULL, NULL, NULL, 145),
(142, 'Catholic Conference', NULL, 'F', NULL, NULL, NULL, 146),
(143, 'Merrimack Valley/Dual County Large', NULL, 'F', NULL, NULL, NULL, 147),
(144, 'Merrimack Valley Conference/Greater Boston League', NULL, 'F', NULL, NULL, NULL, 148),
(145, 'North Cape League', NULL, 'F', NULL, NULL, NULL, 149),
(146, 'Independent', NULL, 'F', NULL, NULL, NULL, 150),
(147, 'Middlesex', NULL, 'F', NULL, NULL, NULL, 151),
(148, 'NORTH CAPE', NULL, 'F', NULL, NULL, NULL, 152),
(149, 'Southeastern Mass GHL North', NULL, 'F', NULL, NULL, NULL, 153),
(150, 'Southeastern Mass GHL South', NULL, 'F', NULL, NULL, NULL, 154),
(151, 'Atlantic Coast', NULL, 'M', NULL, NULL, NULL, 155),
(152, 'Greater Boston League', NULL, 'F', NULL, NULL, NULL, 156),
(153, 'Merrimack Valley/Dual County Small', NULL, 'F', NULL, NULL, NULL, 157),
(154, 'Middlesex League Freedom Division', NULL, 'M', NULL, NULL, NULL, 158),
(155, 'SEMGHL Northeast', NULL, 'F', NULL, NULL, NULL, 159),
(156, 'Middlesex League Freedom Division', NULL, 'F', NULL, NULL, NULL, 160),
(157, 'Northeastern Hockey League/South', NULL, 'F', NULL, NULL, NULL, 161),
(158, 'Dual County Large', NULL, 'F', NULL, NULL, NULL, 164),
(159, 'SEMGHL Southeast', NULL, 'F', NULL, NULL, NULL, 165),
(160, 'Patriot League Keenan Division', NULL, 'M', NULL, NULL, NULL, 166),
(161, 'SEMGHL', NULL, 'F', NULL, NULL, NULL, 167),
(162, 'XX Archive (Obsolete Teams) League', NULL, 'F', NULL, NULL, NULL, 168),
(163, 'XX Archive (Obsolete Teams) League', NULL, 'M', NULL, NULL, NULL, 169),
(164, 'Patriot League', NULL, 'F', NULL, NULL, NULL, 170),
(165, 'Atlantic Coast League', NULL, 'F', NULL, NULL, NULL, 171),
(166, 'Hockomock', NULL, 'F', NULL, NULL, NULL, 172),
(167, 'Tri-Valley League', NULL, 'F', NULL, NULL, NULL, 173),
(168, 'Tri-Valley League Small', NULL, 'M', NULL, NULL, NULL, 174),
(169, 'Cape &#38; Islands League', NULL, 'M', NULL, NULL, NULL, 175),
(170, 'Tri-Valley League', NULL, 'M', NULL, NULL, NULL, 176),
(171, 'Pioneer Valley Fay-Wright Division', NULL, 'M', NULL, NULL, NULL, 177),
(172, 'Middlesex Large', NULL, 'M', NULL, NULL, NULL, 178),
(173, 'Middlesex Large', NULL, 'F', NULL, NULL, NULL, 179),
(174, 'Middlesex Small', NULL, 'M', NULL, NULL, NULL, 180),
(175, 'Middlesex Small', NULL, 'F', NULL, NULL, NULL, 181),
(176, 'Hockomock', NULL, 'M', NULL, NULL, NULL, 182),
(177, 'Middlesex League', NULL, 'M', NULL, NULL, NULL, 183),
(178, 'Dual County Large', NULL, 'F', NULL, NULL, NULL, 184),
(179, 'Dual County Small', NULL, 'F', NULL, NULL, NULL, 185),
(180, 'Merrimack Valley/Greater Boston', NULL, 'F', NULL, NULL, NULL, 186),
(181, 'Middlesex League', NULL, 'F', NULL, NULL, NULL, 187),
(182, 'North Cape League', NULL, 'F', NULL, NULL, NULL, 188),
(183, 'Southeastern Mass GHL North', NULL, 'F', NULL, NULL, NULL, 189),
(184, 'Southeastern Mass GHL South', NULL, 'F', NULL, NULL, NULL, 190),
(185, 'Patriot League', NULL, 'M', NULL, NULL, NULL, 191),
(186, 'GEMIHL Central/West', NULL, 'F', NULL, NULL, NULL, 192),
(187, 'Middlesex Large', NULL, 'F', NULL, NULL, NULL, 193),
(188, 'SEMGHL', NULL, 'F', NULL, NULL, NULL, 194),
(189, 'North Cape League', NULL, 'F', NULL, NULL, NULL, 195),
(190, 'GEMIHL Northeast', NULL, 'F', NULL, NULL, NULL, 196),
(191, 'Northeastern Hockey League/North', NULL, 'F', NULL, NULL, NULL, 197),
(192, 'SEMGHL East', NULL, 'F', NULL, NULL, NULL, 198),
(193, 'Middlesex Small', NULL, 'F', NULL, NULL, NULL, 199),
(194, 'GEMIHL Metro', NULL, 'F', NULL, NULL, NULL, 200);
