-- teams: 539 records

INSERT INTO teams (id, name, gender) VALUES
  (1, 'Abington', 'M'),
  (2, 'Acton-Boxboro', 'M'),
  (3, 'Agawam', 'M'),
  (4, 'Algonquin', 'M'),
  (5, 'Amesbury', 'M'),
  (6, 'Amherst-Pelham', 'M'),
  (7, 'Andover', 'M'),
  (8, 'Archbishop Williams', 'M'),
  (9, 'Arlington', 'M'),
  (10, 'Arlington Catholic', 'M'),
  (11, 'Ashland', 'M'),
  (12, 'Assabet', 'M'),
  (13, 'Attleboro', 'M'),
  (14, 'Auburn/Millbury', 'M'),
  (15, 'Austin Prep', 'M'),
  (17, 'Barnstable', 'M'),
  (18, 'BC High', 'M'),
  (19, 'Bedford', 'M'),
  (20, 'Belchertown', 'M'),
  (21, 'Bellingham', 'M'),
  (22, 'Belmont', 'M'),
  (23, 'Beverly', 'M'),
  (24, 'Billerica', 'M'),
  (25, 'Apponequet/Connolly', 'M'),
  (26, 'Bishop Feehan', 'M'),
  (27, 'Bishop Fenwick', 'M'),
  (28, 'Bishop Stang', 'M'),
  (30, 'Blue Hills', 'M'),
  (31, 'Boston Latin', 'M'),
  (32, 'Bourne', 'M'),
  (33, 'Braintree', 'M'),
  (34, 'Bridgewater-Raynham', 'M'),
  (35, 'Brockton', 'M'),
  (36, 'Brookline', 'M'),
  (37, 'Burlington', 'M'),
  (38, 'Cambridge', 'M'),
  (39, 'Canton', 'M'),
  (40, 'Cape Tech/Cape Cod Academy', 'M'),
  (42, 'Catholic Memorial', 'M'),
  (43, 'Central Catholic', 'M'),
  (44, 'Chelmsford', 'M'),
  (45, 'Chicopee', 'M'),
  (46, 'Chicopee Comp', 'M'),
  (47, 'Cohasset', 'M'),
  (48, 'Concord-Carlisle', 'M'),
  (49, 'Coyle & Cassidy', 'M'),
  (50, 'Danvers', 'M'),
  (51, 'Dartmouth', 'M'),
  (52, 'Dedham', 'M'),
  (53, 'Dennis-Yarmouth', 'M'),
  (54, 'Diman', 'M'),
  (55, 'Dover-Sherborn', 'M'),
  (56, 'Dracut', 'M'),
  (58, 'Durfee', 'M'),
  (59, 'Duxbury', 'M'),
  (60, 'East Boston', 'M'),
  (61, 'East Longmeadow', 'M'),
  (62, 'Easthampton', 'M'),
  (63, 'Everett', 'M'),
  (64, 'Falmouth', 'M'),
  (66, 'Foxboro', 'M'),
  (67, 'Framingham', 'M'),
  (68, 'Franklin', 'M'),
  (69, 'Gardner/Murdock', 'M'),
  (70, 'Gloucester', 'M'),
  (71, 'Grafton/BVT', 'M'),
  (72, 'Greater New Bedford', 'M'),
  (73, 'Greenfield', 'M'),
  (77, 'Haverhill', 'M'),
  (78, 'Hingham', 'M'),
  (79, 'Holliston', 'M'),
  (80, 'South Hadley/Holyoke', 'M'),
  (81, 'Hopkinton', 'M'),
  (82, 'Hudson', 'M'),
  (84, 'Middleboro/Hull', 'M'),
  (85, 'King Philip', 'M'),
  (86, 'Latin Academy', 'M'),
  (88, 'Lexington', 'M'),
  (89, 'Lincoln-Sudbury', 'M'),
  (90, 'Littleton/Bromfield', 'M'),
  (91, 'Longmeadow', 'M'),
  (92, 'Lowell', 'M'),
  (93, 'Ludlow', 'M'),
  (94, 'Lunenburg/Ayer-Shirley', 'M'),
  (95, 'Lynn', 'M'),
  (97, 'Lynnfield', 'M'),
  (98, 'Malden Catholic', 'M'),
  (99, 'Mansfield', 'M'),
  (100, 'Marblehead', 'M'),
  (101, 'Marian', 'M'),
  (102, 'Marlboro', 'M'),
  (103, 'Marshfield', 'M'),
  (104, 'Marthas Vineyard', 'M'),
  (105, 'Masconomet', 'M'),
  (106, 'Mashpee/Monomoy', 'M'),
  (107, 'Matignon', 'M'),
  (108, 'Medfield', 'M'),
  (110, 'Medway', 'M'),
  (112, 'Methuen', 'M'),
  (114, 'Milford', 'M'),
  (115, 'Milton', 'M'),
  (116, 'Minnechaug', 'M'),
  (117, 'Minuteman', 'M'),
  (118, 'Mt Everett', 'M'),
  (120, 'Nashoba Tech', 'M'),
  (121, 'Nashoba', 'M'),
  (122, 'Natick', 'M'),
  (123, 'Nauset', 'M'),
  (124, 'Needham', 'M'),
  (125, 'New Bedford', 'M'),
  (126, 'Newburyport', 'M'),
  (127, 'Newton North', 'M'),
  (128, 'Newton South', 'M'),
  (129, 'North Andover', 'M'),
  (130, 'North Attleboro', 'M'),
  (131, 'North Middlesex', 'M'),
  (132, 'North Quincy', 'M'),
  (133, 'North Reading', 'M'),
  (134, 'Northbridge', 'M'),
  (135, 'Northeast', 'M'),
  (136, 'Norwell', 'M'),
  (137, 'Norwood', 'M'),
  (138, 'Oakmont/Narragansett', 'M'),
  (139, 'Old Rochester/Fairhaven', 'M'),
  (140, 'Oliver Ames', 'M'),
  (141, 'Peabody', 'M'),
  (142, 'Pembroke', 'M'),
  (143, 'Pentucket', 'M'),
  (145, 'Plymouth South', 'M'),
  (147, 'Quincy', 'M'),
  (148, 'Reading', 'M'),
  (149, 'Revere', 'M'),
  (150, 'Rockland', 'M'),
  (151, 'Rockport/Manchester Essex', 'M'),
  (152, 'Salem/Hamilton Wenham', 'M'),
  (153, 'Sandwich', 'M'),
  (154, 'Saugus', 'M'),
  (155, 'Scituate', 'M'),
  (156, 'Shawsheen', 'M'),
  (157, 'Shrewsbury', 'M'),
  (158, 'Silver Lake', 'M'),
  (159, 'OBryant', 'M'),
  (160, 'Somerset Berkley', 'M'),
  (161, 'Somerville', 'M'),
  (163, 'South Shore Voc-Tech', 'M'),
  (164, 'Southeastern/West Bridgewater', 'M'),
  (165, 'Springfield Cathedral', 'M'),
  (167, 'St Bernards', 'M'),
  (168, 'St Johns (S)', 'M'),
  (169, 'St Johns Prep', 'M'),
  (170, 'St Marys Lynn', 'M'),
  (171, 'St Peter Marian', 'M'),
  (174, 'St Mary Westfield', 'M'),
  (175, 'Stoneham', 'M'),
  (176, 'Stoughton', 'M'),
  (184, 'Turners Falls', 'M'),
  (177, 'Swampscott', 'M'),
  (178, 'Taconic/Pittsfield', 'M'),
  (179, 'Taunton', 'M'),
  (180, 'Tewksbury', 'M'),
  (181, 'Tri-County', 'M'),
  (182, 'St Joseph Prep', 'M'),
  (183, 'Triton', 'M'),
  (186, 'Wachusett', 'M'),
  (187, 'Wahconah', 'M'),
  (188, 'Wakefield', 'M'),
  (189, 'Walpole', 'M'),
  (190, 'Waltham', 'M'),
  (191, 'Wareham/Carver', 'M'),
  (192, 'Watertown', 'M'),
  (193, 'Wayland', 'M'),
  (194, 'Wellesley', 'M'),
  (196, 'West Springfield', 'M'),
  (197, 'Westboro', 'M'),
  (198, 'Westfield', 'M'),
  (199, 'Westford Academy', 'M'),
  (200, 'Weston', 'M'),
  (201, 'Westwood', 'M'),
  (202, 'Weymouth', 'M'),
  (203, 'Whitman-Hanson', 'M'),
  (204, 'Wilmington', 'M'),
  (205, 'Winchester', 'M'),
  (206, 'Winthrop', 'M'),
  (207, 'Woburn', 'M'),
  (208, 'Worcester/Leicester', 'M'),
  (209, 'Xaverian', 'M'),
  (210, 'Acton-Boxboro', 'F'),
  (211, 'Algonquin/Hudson', 'F'),
  (212, 'Andover', 'F'),
  (213, 'Archbishop Williams', 'F'),
  (214, 'Arlington', 'F'),
  (215, 'Arlington Catholic', 'F'),
  (216, 'Austin Prep', 'F'),
  (217, 'Barnstable', 'F'),
  (219, 'Beverly/Danvers', 'F'),
  (220, 'Billerica', 'F'),
  (221, 'Boston Latin', 'F'),
  (222, 'Braintree', 'F'),
  (223, 'Burlington', 'F'),
  (225, 'Canton', 'F'),
  (227, 'Concord-Carlisle', 'F'),
  (228, 'Dedham', 'F'),
  (229, 'Dover-Sherborn/Hopkinton', 'F'),
  (230, 'Duxbury', 'F'),
  (232, 'Falmouth', 'F'),
  (233, 'Fontbonne Academy', 'F'),
  (234, 'Framingham', 'F'),
  (235, 'Franklin', 'F'),
  (237, 'Hingham', 'F'),
  (238, 'Latin Academy/St Joseph Prep', 'F'),
  (239, 'Lexington', 'F'),
  (240, 'Lincoln-Sudbury', 'F'),
  (241, 'Winthrop/Lynn', 'F'),
  (242, 'Marblehead', 'F'),
  (243, 'Marshfield', 'F'),
  (244, 'Marthas Vineyard', 'F'),
  (245, 'Masconomet', 'F'),
  (247, 'Medfield', 'F'),
  (248, 'Medford', 'F'),
  (249, 'Milton', 'F'),
  (251, 'Natick', 'F'),
  (252, 'Needham', 'F'),
  (253, 'Newton North', 'F'),
  (255, 'Quincy/North Quincy', 'F'),
  (256, 'Norwood', 'F'),
  (257, 'Notre Dame Academy Hingham', 'F'),
  (258, 'Peabody/Lynnfield', 'F'),
  (259, 'Reading', 'F'),
  (260, 'Sandwich', 'F'),
  (261, 'Shawsheen', 'F'),
  (263, 'St Marys Lynn', 'F'),
  (264, 'Stoneham', 'F'),
  (265, 'Ursuline Academy', 'F'),
  (266, 'Wakefield', 'F'),
  (267, 'Walpole', 'F'),
  (268, 'Waltham', 'F'),
  (269, 'Watertown/Belmont', 'F'),
  (270, 'Wayland/Weston', 'F'),
  (271, 'Wellesley', 'F'),
  (272, 'Westford Academy', 'F'),
  (273, 'Westwood', 'F'),
  (275, 'Wilmington', 'F'),
  (276, 'Winchester', 'F'),
  (277, 'Woburn', 'F'),
  (281, 'Weymouth', 'F'),
  (282, 'Brookline/Newton South', 'F'),
  (283, 'King Philip', 'F'),
  (284, 'Scituate', 'F'),
  (285, 'Shrewsbury', 'F'),
  (287, 'Lowell Catholic', 'M'),
  (288, 'Dighton-Rehoboth/Seekonk', 'M'),
  (289, 'Mystic Valley', 'M'),
  (291, 'Medway/Ashland', 'F'),
  (292, 'Nantucket', 'M'),
  (293, 'Auburn', 'F'),
  (585, 'East Bridgewater', 'M'),
  (586, 'Cohasset/Hanover', 'F'),
  (587, 'Mansfield/Oliver Ames', 'F'),
  (588, 'Norwell', 'F'),
  (589, 'Bishop Fenwick', 'F'),
  (590, 'Dennis-Yarmouth', 'F'),
  (591, 'Pope John Paul II', 'M'),
  (594, 'Nauset/Cape Cod Tech', 'F'),
  (595, 'Sacred Heart', 'M'),
  (596, 'Bourne/Mashpee/Wareham', 'F'),
  (597, 'Tewksbury/Methuen', 'F'),
  (599, 'Central Catholic', 'F'),
  (600, 'Hopedale/Millis', 'M'),
  (601, 'Norton', 'M'),
  (602, 'Bishop Stang', 'F'),
  (604, 'Haverhill/North Andover', 'F'),
  (605, 'Leominster', 'F'),
  (608, 'Melrose', 'F'),
  (612, 'Oakmont', 'F'),
  (613, 'Plymouth', 'F'),
  (614, 'Cardinal Spellman', 'M'),
  (615, 'Upper Cape Tech', 'M'),
  (616, 'Whitman-Hanson/Silver Lake', 'F'),
  (218, 'Belmont', 'F'),
  (274, 'Pembroke', 'F'),
  (603, 'Nauset/CCT', 'F'),
  (617, 'Longmeadow', 'F'),
  (618, 'Stoughton', 'F'),
  (65, 'Fitchburg/Monty Tech', 'M'),
  (74, 'Groton Dunstable', 'M'),
  (75, 'Hanover', 'M'),
  (87, 'Leominster', 'M'),
  (109, 'Medford', 'M'),
  (111, 'Melrose', 'M'),
  (144, 'Plymouth North', 'M'),
  (224, 'Cambridge', 'F'),
  (246, 'St Joseph Prep/Mt Alvernia', 'F'),
  (606, 'Matignon', 'F'),
  (619, 'Hamilton-Wenham', 'M'),
  (620, 'Essex Tech', 'M'),
  (621, 'St Peter Marian', 'F'),
  (623, 'Drury', 'M'),
  (622, 'Southwick', 'M'),
  (16, 'Avon/Holbrook', 'M'),
  (29, 'Blackstone-Millville', 'M'),
  (41, 'Carver/Sacred Heart', 'M'),
  (57, 'Drury', 'M'),
  (76, 'Harwich/Chatham', 'M'),
  (83, 'Hudson Catholic', 'M'),
  (113, 'Middleboro', 'M'),
  (119, 'Murdock/Athol', 'M'),
  (162, 'South Boston', 'M'),
  (166, 'Springfield Central', 'M'),
  (172, 'St. Clement/Cathedral', 'M'),
  (173, 'St Josephs', 'M'),
  (185, 'Tyngsboro', 'M'),
  (195, 'West Roxbury', 'M'),
  (226, 'Chelmsford', 'F'),
  (231, 'Everett', 'F'),
  (250, 'Mt St Joseph Academy', 'F'),
  (254, 'Newton South', 'F'),
  (262, 'St Peter Marian/St Bernards', 'F'),
  (280, 'Nipmuc', 'M'),
  (286, 'Springfield Cathedral', 'F'),
  (290, 'Gardner/St Bernards', 'F'),
  (96, 'Lynn Tech', 'M'),
  (146, 'Pope John', 'M'),
  (236, 'Gloucester/Manchester Essex', 'F'),
  (279, 'test 2', 'M'),
  (598, 'Mansfield/Oliver Ames', 'F'),
  (624, 'zz The Snoops', 'M'),
  (625, 'zzTestTeam2', 'M'),
  (628, 'lets play a game', 'M'),
  (629, 'Mens Auburn', 'M'),
  (630, 'Atlantic rangers', 'M'),
  (631, 'Austin Prep', 'W'),
  (632, 'Wellesley', 'W'),
  (633, 'Canton', 'W'),
  (634, 'Braintree', 'W'),
  (635, 'Norwell', 'W'),
  (636, 'Woburn', 'W'),
  (637, 'John Paul II', 'M'),
  (638, 'HPNA', 'W'),
  (639, 'St Marys Lynn', 'W'),
  (640, 'Boston Latin', 'W'),
  (641, 'Pope Francis', 'M'),
  (642, 'Arlington', 'W'),
  (643, 'Sandwich', 'W'),
  (644, 'Belmont', 'W'),
  (645, 'Ursuline Acad.', 'W'),
  (646, 'Westwood', 'W'),
  (647, 'Natick', 'W'),
  (648, 'Needham', 'W'),
  (649, 'Shrewsbury', 'W'),
  (650, 'Peabody/Lynnfield/No. Reading', 'M'),
  (651, 'Notre Dame Acad. Hingham', 'M'),
  (652, 'Waltham', 'W'),
  (653, 'Falmouth', 'W'),
  (654, 'Norwood', 'W'),
  (655, 'Dennis-Yarmouth', 'W'),
  (656, 'Hopedale/Milford', 'M'),
  (657, 'Algonquin/Hudson', 'W'),
  (658, 'St Johns Shrewsbury', 'M'),
  (659, 'Nashoba Regional', 'M'),
  (660, 'Methuen/Tewksbury', 'W'),
  (661, 'Duxbury', 'W'),
  (662, 'Bishop Fenwick', 'W'),
  (663, 'Medfield/Norton', 'W'),
  (664, 'Andover', 'W'),
  (665, 'St Peter Marian', 'W'),
  (666, 'Dedham', 'W'),
  (667, 'Reading', 'W'),
  (668, 'Wayland/Weston', 'W'),
  (669, 'Burlington', 'W'),
  (670, 'Hingham', 'W'),
  (671, 'Masconomet', 'W'),
  (672, 'Barnstable', 'W'),
  (673, 'Bishop Stang', 'W'),
  (674, 'Mansfield/OA/Foxboro', 'W'),
  (675, 'Medway/Ashland', 'W'),
  (676, 'Longmeadow', 'W'),
  (677, 'Plymouth', 'W'),
  (678, 'Cohasset/Hanover', 'W'),
  (679, 'Northeast Tech', 'M'),
  (680, 'Lexington', 'W'),
  (681, 'Cape Cod', 'W'),
  (682, 'King Philip', 'W'),
  (683, 'Lincoln-Sudbury', 'W'),
  (684, 'Acton-Boxboro', 'W'),
  (685, 'Matignon', 'W'),
  (686, 'Westford Acad.', 'W'),
  (687, 'Wakefield', 'W'),
  (688, 'Winthrop', 'W'),
  (689, 'Billerica/Chelmsford', 'W'),
  (690, 'Franklin', 'W'),
  (691, 'Cohasset/Hull', 'M'),
  (692, 'Arlington Catholic', 'W'),
  (693, 'Pembroke', 'W'),
  (694, 'Groton-Dunstable', 'M'),
  (695, 'Assabet Valley', 'M'),
  (696, 'Wilmington', 'W'),
  (697, 'Brookline', 'W'),
  (698, 'Walpole', 'W'),
  (699, 'Revere/Malden/Matignon', 'M'),
  (700, 'Winchester', 'W'),
  (701, 'Marblehead', 'W'),
  (702, 'Dover-Sherborn/Weston', 'M'),
  (703, 'Watertown', 'W'),
  (704, 'Auburn', 'W'),
  (705, 'Beverly/Danvers', 'W'),
  (706, 'Milton', 'W'),
  (707, 'Dracut/Tyngsboro', 'M'),
  (708, 'Marthas Vineyard', 'W'),
  (709, 'Archbishop Williams', 'W'),
  (710, 'Old Rochester', 'W'),
  (711, 'Concord-Carlisle', 'W'),
  (712, 'Newton North/Newton South', 'W'),
  (713, 'Quincy/North Quincy', 'W'),
  (714, 'Medford/Malden', 'W'),
  (715, 'Mount Everett', 'M'),
  (716, 'Oakmont', 'W'),
  (717, 'Leominster', 'W'),
  (718, 'Weymouth', 'W'),
  (719, 'Cambridge', 'W'),
  (720, 'Latin Academy/Fontbonne', 'W'),
  (721, 'Stoughton/Brockton', 'M'),
  (722, 'Central Catholic', 'W'),
  (723, 'Stoughton', 'W'),
  (724, 'Greater Lowell/Nashoba Tech', 'M'),
  (725, 'Regis Jesuit (CO)', 'M'),
  (726, 'Woodstock Academy', 'M'),
  (727, 'Bishop Feehan', 'W'),
  (728, 'Scituate', 'W'),
  (729, 'LaSalle Academy (RI)', 'M'),
  (730, 'Woodstock Academy (CT)', 'M'),
  (731, 'Exeter HS (NH)', 'M'),
  (732, 'Barrington (RI)', 'M'),
  (733, 'La Salle (RI)', 'W'),
  (734, 'Shawsheen/Bedford', 'W'),
  (735, 'Marshfield', 'W'),
  (736, 'Dover-Sherborn/Hopkinton', 'W'),
  (737, 'Notre Dame (CT)', 'M'),
  (738, 'Stowe (VT)', 'M'),
  (739, 'Lewiston (ME)', 'M'),
  (740, 'Albany Academy', 'M'),
  (741, 'Rice Prep', 'M'),
  (742, 'Bedford (NH)', 'M'),
  (743, 'East Greenwich (RI)', 'M'),
  (744, 'Enfield (CT)', 'M'),
  (745, 'Suffield Acad. (CT)', 'W'),
  (746, 'Newtown (CT)', 'M'),
  (747, 'Valor Christian (CO)', 'M'),
  (748, 'Essex (VT)', 'W'),
  (749, 'Don Bosco Prep (NJ)', 'M'),
  (750, 'Barrington (RI)', 'W'),
  (751, 'Bishop Guertin (NH)', 'M'),
  (752, 'Delbarton (NJ)', 'M'),
  (753, 'East Catholic', 'W'),
  (754, 'Mt St Charles (RI)', 'M'),
  (755, 'Framingham', 'W'),
  (756, 'Pinkerton Academy (NH)', 'M'),
  (757, 'La Salle College (PA)', 'M'),
  (758, 'North Kingstown (RI)', 'M'),
  (759, 'Rogers/Middletown (RI)', 'M'),
  (760, 'Fairfield Prep (CT)', 'M'),
  (761, 'Burrillville (RI)', 'M'),
  (762, 'Mt St Charles (RI)', 'W'),
  (763, 'St Dominics (ME)', 'M'),
  (764, 'Prout School (RI)', 'M'),
  (765, 'TBD', 'M'),
  (766, 'Salem (NH)', 'M'),
  (767, 'Londonderry (NH)', 'M'),
  (768, 'Middlebury Union (VT)', 'M'),
  (769, 'St. Thomas Aquinas', 'M'),
  (770, 'Edward Little (ME)', 'M'),
  (771, 'Moses Brown (RI)', 'M'),
  (772, 'Cumberland (RI)', 'M'),
  (773, 'St Francis', 'M'),
  (774, 'Bishop Hendricken (RI)', 'M'),
  (775, 'Biddeford (ME)', 'M'),
  (776, 'Yarmouth (ME)', 'M'),
  (777, 'Scarborough (ME)', 'M'),
  (778, 'BFA St Albans', 'W'),
  (779, 'Smithfield (RI)', 'M'),
  (780, 'Stoneham/Melrose', 'W'),
  (781, 'Nantucket', 'W'),
  (782, 'York (ME)', 'M'),
  (783, 'Hanover W (NH)', 'M'),
  (784, 'Portland (ME)', 'M'),
  (785, 'Oyster River (NH)', 'M'),
  (786, 'Trumbull (CT)', 'M'),
  (787, 'Bishop Guertin (NH)', 'W'),
  (788, 'Exeter (NH)', 'W'),
  (789, 'Cranston West (RI)', 'M'),
  (790, 'Tri-Town (CT)', 'M'),
  (791, 'Missisquoi (VT)', 'M'),
  (792, 'Glastonbury (CT)', 'M'),
  (793, 'Warwick Tolgate (RI)', 'W'),
  (794, 'Shepaug Valley (CT)', 'M'),
  (795, 'North Smithfield (RI)', 'M'),
  (796, 'Mount Hope (RI)', 'M'),
  (797, 'Falmouth (ME)', 'M'),
  (798, 'Newburyport', 'W'),
  (799, 'Pope Francis', 'W'),
  (800, 'Gloucester', 'W'),
  (801, 'Malden Catholic', 'W'),
  (802, 'W/E Bridgewater', 'W'),
  (803, 'St. Bernard''s', 'M'),
  (804, 'TBD', 'W'),
  (805, 'Cape Cod Tech/CCA', 'M'),
  (806, 'Southeastern/Bris.-Plym.', 'M'),
  (807, 'Stoneham/Wilmington', 'M'),
  (808, 'Hanover', 'W'),
  (809, 'Everett/Revere', 'M'),
  (810, 'St Paul Diocesan', 'M'),
  (811, 'Winnacunnet (NH)', 'M'),
  (812, 'Melrose', 'W'),
  (813, 'Northwest Catholic (CT)', 'M'),
  (814, 'Fairfield Prep', 'M'),
  (815, 'St. Rita''s (IL)', 'M'),
  (816, 'Bishop Brady (NH)', 'M'),
  (817, 'Pinkerton Acad. (NH)', 'M'),
  (818, 'Notre Dame-Fairfield (CT)', 'M'),
  (819, 'Milton (VT)', 'M'),
  (820, 'Grafton', 'M'),
  (821, 'Blackstone Valley Tech', 'M'),
  (822, 'East/West Bridgewater', 'M'),
  (823, 'Taconic', 'M'),
  (824, 'Peabody/Saugus', 'M'),
  (825, 'Warwick Co-op (RI)', 'M'),
  (826, 'McCann Tech', 'M'),
  (827, 'Housatonic Co-op', 'M'),
  (828, 'Burrillville Co-Op', 'M'),
  (829, 'St. Thomas Aquinas (NH)', 'M'),
  (830, 'Suffield/Granby/Windsor Locks (CT)', 'M'),
  (831, 'Timberlane Regional (NH)', 'M'),
  (832, 'Rogers/Middletown/RH (RI)', 'M'),
  (833, 'Ponaganset (RI)', 'M'),
  (834, 'Portsmouth (NH)', 'M'),
  (835, 'South Kingstown (RI)', 'M'),
  (836, 'Smithfield HS (RI)', 'M'),
  (837, 'Unknown (6479)', 'M'),
  (838, 'Unknown (0)', 'M'),
  (839, 'Unknown (-1)', 'M');

