-- Schema for MassHSHockey database
-- Generated by split-sql.js

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------
-- Drop tables (reverse FK-safe order)
-- -----------------------------------------------------

DROP TABLE IF EXISTS `staff_teams`;
DROP TABLE IF EXISTS `staff`;
DROP TABLE IF EXISTS `player_game_stats`;
DROP TABLE IF EXISTS `player_seasons`;
DROP TABLE IF EXISTS `players`;
DROP TABLE IF EXISTS `games`;
DROP TABLE IF EXISTS `team_seasons`;
DROP TABLE IF EXISTS `team_id_mapping`;
DROP TABLE IF EXISTS `teams`;
DROP TABLE IF EXISTS `venues`;
DROP TABLE IF EXISTS `divisions`;
DROP TABLE IF EXISTS `leagues`;
DROP TABLE IF EXISTS `seasons`;

-- -----------------------------------------------------
-- Create tables (FK-safe order)
-- -----------------------------------------------------

CREATE TABLE `seasons` (
  `id` int NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `leagues` (
  `id` int NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `short_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'OLD_DB, SPORTSPRESS, or BOTH',
  `old_db_league_id` int DEFAULT NULL,
  `sp_term_id` int DEFAULT NULL,
  `old_db_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `divisions` (
  `id` int NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gender` char(1) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `venues` (
  `id` int NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `old_db_id` int DEFAULT NULL,
  `sp_venue_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `teams` (
  `id` int NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gender` char(1) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'M or F',
  `old_db_team_id` int DEFAULT NULL,
  `sp_post_id` int DEFAULT NULL,
  `mapping_source` enum('BOTH_SYSTEMS','OLD_DB_ONLY','SPORTSPRESS_ONLY') COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `team_id_mapping` (
  `consolidated_team_id` int NOT NULL,
  `team_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gender` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `old_db_team_id` int DEFAULT NULL,
  `sp_post_id` int DEFAULT NULL,
  `sp_team_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mapping_source` enum('BOTH_SYSTEMS','OLD_DB_ONLY','SPORTSPRESS_ONLY') COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Master team ID mapping between Old DB and SportsPress';

CREATE TABLE `team_seasons` (
  `id` int NOT NULL,
  `team_id` int NOT NULL,
  `season_id` int NOT NULL,
  `league_id` int DEFAULT NULL,
  `division_id` int DEFAULT NULL,
  `wins` int DEFAULT '0',
  `losses` int DEFAULT '0',
  `ties` int DEFAULT '0',
  `points` int DEFAULT NULL,
  `goals_for` int DEFAULT '0',
  `goals_against` int DEFAULT '0',
  `win_pct` decimal(5,3) DEFAULT '0.000',
  `source` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'OLD_DB or SPORTSPRESS',
  `source_system` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `games` (
  `id` int NOT NULL,
  `season_id` int DEFAULT NULL,
  `game_date` date DEFAULT NULL,
  `game_time` time DEFAULT NULL,
  `home_team_id` int DEFAULT NULL,
  `away_team_id` int DEFAULT NULL,
  `home_score` int DEFAULT NULL,
  `away_score` int DEFAULT NULL,
  `venue_id` int DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `game_type` varchar(50) DEFAULT NULL,
  `old_db_id` int DEFAULT NULL,
  `source_system` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `players` (
  `id` int NOT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `position` varchar(50) DEFAULT NULL,
  `jersey_number` varchar(20) DEFAULT NULL,
  `height` varchar(20) DEFAULT NULL,
  `weight` varchar(20) DEFAULT NULL,
  `old_db_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `player_seasons` (
  `id` int NOT NULL,
  `player_id` int DEFAULT NULL,
  `season_id` int DEFAULT NULL,
  `team_id` int DEFAULT NULL,
  `team_season_id` int DEFAULT NULL,
  `jersey_number` int DEFAULT NULL,
  `position` char(1) DEFAULT NULL COMMENT 'F, D, G',
  `position_name` varchar(50) DEFAULT NULL,
  `year` varchar(50) DEFAULT NULL,
  `hometown` varchar(100) DEFAULT NULL,
  `is_captain` char(1) DEFAULT 'N',
  `games_played` int DEFAULT NULL,
  `goals` int DEFAULT NULL,
  `assists` int DEFAULT NULL,
  `points` int DEFAULT NULL,
  `penalty_minutes` int DEFAULT NULL,
  `goals_against` int DEFAULT '0',
  `goals_against_average` decimal(5,3) DEFAULT '0.000',
  `shots` int DEFAULT '0',
  `saves` int DEFAULT '0',
  `save_percentage` decimal(5,3) DEFAULT '0.000',
  `shutouts` int DEFAULT '0',
  `minutes` bigint DEFAULT '0',
  `source_system` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `player_game_stats` (
  `id` int NOT NULL,
  `game_id` int DEFAULT NULL,
  `player_id` int DEFAULT NULL,
  `team_id` int DEFAULT '0',
  `goals` int DEFAULT '0',
  `assists` int DEFAULT '0',
  `old_game_id` int DEFAULT NULL,
  `old_player_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `staff` (
  `id` int NOT NULL,
  `first_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT 'Coach',
  `old_db_staff_id` int DEFAULT NULL,
  `sp_post_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `staff_teams` (
  `id` int NOT NULL,
  `staff_id` int NOT NULL,
  `team_id` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Indexes
-- -----------------------------------------------------

ALTER TABLE `seasons`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_dates` (`start_date`,`end_date`);

ALTER TABLE `leagues`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_gender` (`gender`),
  ADD KEY `idx_name` (`name`);

ALTER TABLE `divisions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_gender` (`gender`);

ALTER TABLE `venues`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `teams`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_name` (`name`),
  ADD KEY `idx_gender` (`gender`),
  ADD KEY `idx_old_db` (`old_db_team_id`),
  ADD KEY `idx_sp` (`sp_post_id`);

ALTER TABLE `team_id_mapping`
  ADD PRIMARY KEY (`consolidated_team_id`),
  ADD KEY `idx_old_db` (`old_db_team_id`),
  ADD KEY `idx_sp` (`sp_post_id`),
  ADD KEY `idx_name_gender` (`team_name`,`gender`),
  ADD KEY `idx_source` (`mapping_source`);

ALTER TABLE `team_seasons`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `uk_team_season` (`team_id`,`season_id`),
  ADD KEY `idx_season` (`season_id`),
  ADD KEY `idx_league` (`league_id`),
  ADD KEY `idx_division` (`division_id`);

ALTER TABLE `games`
  ADD PRIMARY KEY (`id`),
  ADD KEY `venue_id` (`venue_id`),
  ADD KEY `idx_games_old_db` (`old_db_id`,`source_system`);

ALTER TABLE `players`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `player_seasons`
  ADD PRIMARY KEY (`id`),
  ADD KEY `player_id` (`player_id`),
  ADD KEY `idx_team_season` (`team_season_id`);

ALTER TABLE `player_game_stats`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_game` (`game_id`),
  ADD KEY `idx_player` (`player_id`);

ALTER TABLE `staff`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_name` (`last_name`,`first_name`),
  ADD KEY `idx_old_db` (`old_db_staff_id`),
  ADD KEY `idx_sp` (`sp_post_id`);

ALTER TABLE `staff_teams`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_staff` (`staff_id`),
  ADD KEY `idx_team` (`team_id`);

-- -----------------------------------------------------
-- Auto-increment values
-- -----------------------------------------------------

ALTER TABLE `leagues`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=195;

ALTER TABLE `venues`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=265;

ALTER TABLE `team_seasons`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5706;

ALTER TABLE `games`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44780;

ALTER TABLE `players`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49084;

ALTER TABLE `player_seasons`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49084;

ALTER TABLE `player_game_stats`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49583;

ALTER TABLE `staff`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9953;

ALTER TABLE `staff_teams`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=301;

-- -----------------------------------------------------
-- Foreign key constraints
-- -----------------------------------------------------

ALTER TABLE `team_seasons`
  ADD CONSTRAINT `team_seasons_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),
  ADD CONSTRAINT `team_seasons_ibfk_2` FOREIGN KEY (`season_id`) REFERENCES `seasons` (`id`),
  ADD CONSTRAINT `team_seasons_ibfk_3` FOREIGN KEY (`league_id`) REFERENCES `leagues` (`id`),
  ADD CONSTRAINT `team_seasons_ibfk_4` FOREIGN KEY (`division_id`) REFERENCES `divisions` (`id`);

ALTER TABLE `games`
  ADD CONSTRAINT `games_ibfk_1` FOREIGN KEY (`venue_id`) REFERENCES `venues` (`id`);

ALTER TABLE `player_seasons`
  ADD CONSTRAINT `player_seasons_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`),
  ADD CONSTRAINT `player_seasons_ibfk_2` FOREIGN KEY (`team_season_id`) REFERENCES `team_seasons` (`id`);

ALTER TABLE `staff_teams`
  ADD CONSTRAINT `staff_teams_ibfk_1` FOREIGN KEY (`staff_id`) REFERENCES `staff` (`id`),
  ADD CONSTRAINT `staff_teams_ibfk_2` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`);

SET FOREIGN_KEY_CHECKS = 1;

-- -----------------------------------------------------
-- Views
-- -----------------------------------------------------

CREATE OR REPLACE VIEW v_standings AS
SELECT ts.id, t.name AS team, t.gender, s.name AS season,
       l.name AS league, d.name AS division,
       ts.wins, ts.losses, ts.ties, ts.points,
       ts.goals_for, ts.goals_against,
       (ts.goals_for - ts.goals_against) AS goal_diff, ts.win_pct
FROM team_seasons ts
JOIN teams t ON ts.team_id = t.id
JOIN seasons s ON ts.season_id = s.id
LEFT JOIN leagues l ON ts.league_id = l.id
LEFT JOIN divisions d ON ts.division_id = d.id;

CREATE OR REPLACE VIEW v_schedule AS
SELECT g.id, g.game_date, g.game_time, s.name AS season,
       ht.name AS home_team, g.home_score,
       at2.name AS away_team, g.away_score,
       v.name AS venue, g.status, g.game_type
FROM games g
JOIN teams ht ON g.home_team_id = ht.id
JOIN teams at2 ON g.away_team_id = at2.id
JOIN seasons s ON g.season_id = s.id
LEFT JOIN venues v ON g.venue_id = v.id;

CREATE OR REPLACE VIEW v_player_stats AS
SELECT ps.id, p.first_name, p.last_name,
       CONCAT(p.first_name, ' ', p.last_name) AS player_name,
       t.name AS team, s.name AS season,
       ps.jersey_number, ps.position_name, ps.year,
       ps.games_played, ps.goals, ps.assists,
       (ps.goals + ps.assists) AS total_points,
       ps.goals_against, ps.goals_against_average, ps.save_percentage
FROM player_seasons ps
JOIN players p ON ps.player_id = p.id
JOIN teams t ON ps.team_id = t.id
JOIN seasons s ON ps.season_id = s.id;
